### PR TITLE
2020-11-24 update

### PR DESCRIPTION
**Pull request by beckyjackson**
## New Terms

This PR adds two new species:
* giant panda (NCBITaxon:9646)
* grass carp (NCBITaxon:7959)

It adds 18 terms related to these new species:

ID | Label
-- | --
MRO:0036986 | giant panda MHC class I locus
MRO:0036987 | giant panda MHC class II locus
MRO:0036988 | grass carp MHC class I locus
MRO:0036989 | grass carp MHC class II locus
MRO:0036990 | Aime-128 locus
MRO:0036991 | Ctid-UAA locus
MRO:0036992 | Aime-128 chain
MRO:0036993 | Ctid-UAA chain
MRO:0037012 | Aime-128 protein complex
MRO:0037013 | Ctid-UAA protein complex
MRO:0037032 | giant panda MHC class I chain
MRO:0037033 | giant panda MHC class II chain
MRO:0037034 | grass carp MHC class I chain
MRO:0037035 | grass carp MHC class II chain
MRO:0037036 | giant panda MHC class I protein complex
MRO:0037037 | giant panda MHC class II protein complex
MRO:0037038 | grass carp MHC class I protein complex
MRO:0037039 | grass carp MHC class II protein complex

As well as 36 new HLA terms (18 chain terms and 18 protein complex terms)

## Code Changes

I updated `src/clean.py` to include these two new species with the codes Ctid (grass carp) and Amie (giant panda). Question for @jamesaoverton and/or @rvita - should the code for "chicken" actually be "Gaga" to match with the other terms? Same with duck (Anpl), clawed frog (Xela), etc. See here:
https://github.com/IEDB/MRO/blob/5be1c689c04fc523036f5480cd38eaa3a16bdf3c/src/clean.py#L57-L80

I also updated `src/update_seqs.py` to have an `-o`/`--overwrite` flag. There are now two tasks for sequences (I was getting sick of doing this manually because some of the HLA terms have updates that we don't want to include):
* `update-seqs`: adds sequences where missing
* `refresh-seqs`: adds sequences where missing & overwrites old ones with changes (if any change)

### CODE REVIEW

**Comment by jamesaoverton** [comment]
I think that if I used a common name instead of a prefix it was only because I didn't know the proper prefix. It would be good to put these in the `external.tsv` #65.

**Comment by beckyjackson** [comment]
@jamesaoverton I was thinking we'd merge this first and then make that update. Or should I make that update first?

**Comment by jamesaoverton** [comment]
The release can wait a day or two, but I'd like it done in time for the next IEDB build.

**Comment by beckyjackson** [comment]
OK - I just added the `clean.py` script update to this PR. `external` has a new column: "Species Code"

**Review by jamesaoverton — APPROVED** [review]
My only worry is that the new HLAs should also be in `iedb.tsv`. Please check with Randi. Other than that, it looks good.

**Pull request merged**
