### PR TITLE
Add validation script

### PR DESCRIPTION
**Pull request by beckyjackson**
**This will report errors on the ROBOT validation rows** - but I plan to remove these rows on all templates once MRO `master` is up-to-date with all the other PRs we have open now.

Run `make build/validation_errors.tsv` to see results. You can use `cogs apply` to view these errors in Google Sheets (assuming you have all sheets added to your COGS project)

### CODE REVIEW

**Review by jamesaoverton — APPROVED** [review]
I tried this out and got error for all the ROBOT validate rows, as expected. I just skimmed the code, but I'm not worried about it.

**Comment by jamesaoverton** [comment]
@acrinklaw This PR is for nearly instant validation of larger tables. Would it be better for us to merge this now, or wait on your HLA PR?

**Comment by acrinklaw** [comment]
It's up to you, I'll be pushing my final changes tomorrow if you'd like to wait. Sorry for the delay, I've got quite a bit on my plate for a publication we are trying to get out.

**Comment by beckyjackson** [comment]
@jamesaoverton do you want me to get this merged into `master` and then merge it into the IMGT update so we can test it over that data?

**Comment by jamesaoverton** [comment]
Sure, whatever is easiest.

**Pull request merged**
