### PR TITLE
Add simple flask app for MRO

### PR DESCRIPTION
**Pull request by beckyjackson**
Right now, this is just a home page and a browser.

The content of the home page can be updated by editing `src/site/index.md`. I left it very simple for now, I'm not sure what we want to include here.

Run the app from the top level:
```
export FLASK_APP=src/site/run.py
flask run
```

### CODE REVIEW

**Comment by jamesaoverton** [comment]
Please make the table from #101 downloadable through this site (if it isn't already).

**Comment by beckyjackson** [comment]
Should it be a link in the navbar (like exports?) or should I just route a path to return it as a download?

**Comment by beckyjackson** [comment]
OK, I added a path that they can download it: `/export/molecule_export.tsv`

This will work for any TSV in the build directory, so you could also retrieve the other TSVs that we create for IEDB. It's TSVs only right now, I don't think there's any need to download the OWL files, etc.

**Review by jamesaoverton — APPROVED** [review]
I haven't tested this, but let's just merge and make changes later.

**Pull request merged**
